### ISSUE TITLE
doesn't work on some mobile browser

### ISSUE THREAD

**Issue by mjisican** [jcblw/react-sprite-animator#12]
i tried testing with the default browser of an oppo phone. the component doest show up... works fine on google mobile, firefox mobile and safari mobile though. let me try on other android devices.
I think this is not a major issue.

**Comment by jcblw** [comment]
Do you have any information on which browser do not work?

**Comment by mjisican** [comment]
updated description :)

**Comment by jcblw** [comment]
doing some cleanup of this repo, assuming phones have got better over the years. I am going to close this, feel free to reopen if 2.0 does not help with this.
