### ISSUE TITLE
"startFrame" value not effecting animation

### ISSUE THREAD

**Issue by iksnae** [jcblw/react-sprite-animator#16]
i'm trying to use startFrame value but animations still starting at 0. is there something i'm doing wrong?

`<SpriteAnimator startFrame={1} frameCount={10} sprite={sheetFile} width={150} height={150}/>`

**Comment by LukaszKiedrowski** [comment]
I have the same issue.

please take a look at this line.
https://github.com/jcblw/react-sprite-animator/blob/master/src/index.js#L102

after next loop animation starting from first frame.
for me it should look assign frame props.

```
const startFrame = this.props.startFrame || 0;
const nextFrame = currentFrame + 1 >= maxFrames ? startFrame : currentFrame + 1
```

**Comment by jcblw** [comment]
@LukaszKiedrowski open to a PR if you think you have a fix for this 😄

**Comment by jcblw** [comment]
@LukaszKiedrowski not sure if that is the fix for this, that would just make every time the animation restarts the first frame.
