### ISSUE TITLE
How can I get the first frame Image

### ISSUE THREAD

**Issue by YashaswiMaharshi** [jcblw/react-sprite-animator#19]
Hi, 
How can I bring back the first image, once I have done with the animation of sprite image. Kindly help

**Comment by dlindenkreuz** [comment]
There is no "official" way right now.

However, you may try passing a `reset` prop — if its value transitions from `false` to `true`, the first frame should get restored.

```jsx
// absolutely not tested, take care
class Example extends React.Component {
  doStuff() {
    this.setState({ animate: true })
    setTimeout(() => this.setState({ animate: false }), 1000)
  }

  render() {
    return <SpriteAnimator
      reset={!this.state.animate}
      shouldAnimate={this.state.animate}
    />
  }
}
```

@jcblw Maybe it makes sense to introduce some kind of callback props e.g. for when a loop ends or when the frame number gets increased.

**Comment by jcblw** [comment]
Closing this issue since we just did a big refactor of this. Assume this should still behave the same way as this did in the past. Open to start the dialog again though.
