### ISSUE TITLE
New Release for react 16?

### ISSUE THREAD

**Issue by BuffaloBuffalo** [jcblw/react-sprite-animator#35]
I see there's been recent commits updating the peer dependency for react 16.  Is there any plans to do a publish to get rid of the pesky `npm WARN react-sprite-animator@1.2.0 requires a peer of react@0.13.x || 0.14.x || ^15.x but none is installed. You must install peer dependencies yourself.` warnings?

**Comment by jcblw** [comment]
Hey there yes just added in the code to do all this last night, will try to cut a release later today that updates this. I'll post back in this ticket once it is published.

**Comment by jcblw** [comment]
1.3.0 is published

https://www.npmjs.com/package/react-sprite-animator/v/1.3.0
