### ISSUE TITLE
Feature Request: Complete Event -> Bug: onEnd fires at start

### ISSUE THREAD

**Issue by htopia** [jcblw/react-sprite-animator#60]
Hi there,
First of all thank you so much for this simple and lightweight library, it's been super helpful!
I was wondering if we could get a complete event when an animation is finished.
It could also come in handy being able to trigger an event on a specific frame, so we can play sound effects and stuff like that.
Let me know if this is already supported.
Thanks again!

**Comment by jcblw** [comment]
@htopia thank you! 

We do currently have an `onEnd` event. This only fire if you have `stopLastFrame` set to true. Does this allow you to do what you need or do you have something else in mind?

**Comment by htopia** [comment]
hi @jcblw 
Thank you for replying back.
onEnd sounded like just what I needed, however I just tried it and it seems to be getting triggered on start and end.
You can see the behavior here: https://codesandbox.io/s/cocky-jepsen-fgpz0

**Comment by jcblw** [comment]
@htopia interesting that's not good. Ok seems like a bug. Let's get that fixed.

**Comment by jcblw** [comment]
This should be all good now.
